export const RECIEVE_CURRENT_WEATHER_PENDING = 'RECIEVE_CURRENT_WEATHER_PENDING';
export const RECIEVE_CURRENT_WEATHER_SUCCESS = 'RECIEVE_CURRENT_WEATHER_SUCCESS';
export const RECIEVE_CURRENT_WEATHER_ERROR = 'RECIEVE_CURRENT_WEATHER_ERROR';
